config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do 
  	match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end 

  devise_for :users
  resources :r_apps

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :r_app
end

app/models/r_app.rb
class RApp < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  has_many :r_apps
end

app/controllers/api/events_controller.rb
 class API::EventsController < ApplicationController
   skip_before_action :verify_authenticity_token
   skip_before_action :authenticate_user!
   before_action :set_access_control_headers

   def set_access_control_headers
     headers['Access-Control-Allow-Origin'] = '*'
     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

   def create
 	r_app = RApp.find_by(url: request.env['HTTP_ORIGIN'])

 	if r_app
 		@event = r_app.events.new(event_params)
	 	  if @event.save
			render json: @event, status: :created
	      else
			render json: {errors: @event.errors}, status: :unprocessable_entity 
		  end	
	else
	 	render json: "Unregistered application", status: :unprocessable_entity 
	end
	end 

	def preflight
		head 200
	end 

	private

	def event_params
		params.require(:event).permit(:name)
	end 

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/r_apps_controller.rb
class RAppsController < ApplicationController
  before_action :authenticate_user!

  def index
    @r_apps = RApp.where(user_id: current_user.id)
    flash[:notice] = "User ID not found" if current_user.nil?
  end

  def show
    @r_app = current_user.r_apps.find(params[:id])

    @events = @r_app.events.group_by(&:name)
  end

  def new
    @r_app = RApp.new
  end

  def create
    @r_app = RApp.new(r_app_params)
    @r_app.user = current_user 
    
      if @r_app.save
        flash[:notice] = "Application was registered successfully"
        redirect_to @r_app 
      else
        flash.now[:alert] = "Error registering application. Please try again"
        render :new
      end 
  end 

  def edit
    # @r_app = RApp.find(params[:id])
    @r_app = current_user.r_apps.find(params[:id])
  end

  def update
     # @r_app = RApp.find(params[:id])
     @r_app = current_user.r_apps.find(params[:id])
     @r_app.assign_attributes(r_app_params)

      if @r_app.save
        flash[:notice] = "#{@r_app.name} was updated successfully."
        redirect_to @r_app
      else
        flash.now[:alert] = "Error registering application. Please try again."
        render :edit
      end
  end

  def destroy
    @r_app = RApp.find(params[:id])

     if @r_app.destroy
       flash[:notice] = "\"#{@r_app.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the registered_application."
       render :show
     end
  end

  private 

  def r_app_params
    params.require(:r_app).permit(:name, :url)
  end 
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/r_apps_helper.rb
module RAppsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<title>SiteMetrics</title>
</head>
<body>
 <%= render 'shared/navigation' %>
 <main id="main-container" role="main" class="container">
    <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert bg-info alert-#{name}" %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <!-- sidebar content -->
        </div>
        <div id="content" class="col-xs-9">
          <!--  main content -->
          <%= yield %>   
        </div>
    </main>
    <div id="push"></div>
  </div>
 <%= render 'shared/footer' %>
 <% debug(params) if Rails.env.development? %>
</body>
</html>

app/views/r_apps/_form.html.erb
<%= form_for @r_app do |f| %>
	<div class="form-group">
 		<%= f.label :name%>
 	    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter site name' %>
 	</div>
	<div class="form-group">
		<%= f.label :url %>
		<%= f.text_field :url, class: 'form-control', placeholder: 'Enter site url' %>
  	</div>
	<div class="form-group">
	<%= f.submit "Save", :class => 'btn btn-md btn-primary' %>
	</div>
<% end %>

app/views/r_apps/edit.html.erb
<div class="row">
  <h1>All Applications</h1>
</div>
<div class="row">
   <div class="col-md-8">
     <%= render partial: 'form', locals: { r_app: @r_app} %>
   </div>
 </div>

app/views/r_apps/index.html.erb
<div class="row">
  <h1>All Applications</h1>

  <div class="col-md-4">
      <%= link_to "Register an Application", new_r_app_path, class: "btn btn-success" %>
  </div>
  <hr>

  <div class='row'>
    <div class='col-md-8'>
     <% @r_apps.each do |r| %>
       <div class='media'>
         <div class="media-body">
           <h4 class="media-heading">
      	     <%= link_to r.name, r %>
           </h4>
      	   <small><%= r.url %></small>
         </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/r_apps/new.html.erb
<h1>New Registered Application</h1>
<br>
  <%= render partial: 'form', locals: {r_app: @r_app} %>

app/views/r_apps/show.html.erb
<div class="row">
    <div class="col-md-8">
      <div>
        <h3><%= @r_app.name %></h3>
      </div>

      <div class="row">
       <h4><%= @r_app.url %></h4>
       <% if @events.present? %>
       <h4>Events:</h4>
       <% @events.each do |name, event| %>
           <!-- <%= event %> -->
           <p><%= link_to name, "/#{name}", onclick: 'sitemetrics.report('+"'"+name+"'"+')' %></p>
           <% end %>
            <p><%= pie_chart @r_app.events.group(:name).count%>
            </p>
            <%= line_chart @r_app.events.group_by_day(:created_at).count %>
       <% end %>
      </div>
    </div>

    <div class="col-md-4">
      <%= link_to "Back to index", r_apps_path, class: 'btn btn-primary' %>
      <%= link_to "Edit", edit_r_app_path(@r_app), class: 'btn btn-success' %>
      <%= link_to "Delete", r_app_path(@r_app) , method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this app?'} %>
    </div>
  </div>

app/views/shared/_footer.html.erb
<footer class="bg-dark fixed-bottom text-white mt-5 p-4 text-center">Copyright © 2018 CROMANO</footer>

app/views/shared/_navigation.html.erb
<div class="container">
  <nav class="navbar bg-dark">
      <div class="navbar-header">
        <%if user_signed_in? %>
  	      <%= link_to 'My Profile', edit_user_registration_path, class: "navbar-brand text-light" %>
  	      <%= link_to 'Home', root_path, class: "navbar-brand text-light" %>
  	      <%= link_to "Sign Out", destroy_user_session_path, class: "navbar-brand text-light", method: :delete %>
        <%else %>
  	      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-brand text-light" %>
  	      <%= link_to "Sign In", new_user_session_path, class: "navbar-brand text-light" %>
        <% end %>
      </div>
  </nav>
</div>
  

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to SiteMetrics!</h1>

<%= link_to "See All my Sites", r_apps_path, class: 'btn btn-primary' %>